services:
  career-studio-global:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Ces variables servent au moment du build (Next.js)
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
        - GROQ_API_KEY=${GROQ_API_KEY}
    container_name: career-studio-app
    ports:
      - "3000:3000" # Un seul port pour tout le projet
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always